# =========================== Ingredient Controller ============================= #

@apiUrl = http://localhost:5000
@getIngredientName = *****                            
@getIngredientId = *****
@getCategoryName = *****
@deleteIngredientId = *****

# =============================================================================== #

### Get all ingredients
GET {{apiUrl}}/api/ingredients
Accept: application/json

### Get ingredients by name
GET {{apiUrl}}/api/ingredients/name/{{getIngredientName}}
Accept: application/json

### Get ingredient by id
GET {{apiUrl}}/api/ingredients/id/{{getIngredientId}}
Accept: application/json

### Get ingredients by category
GET {{apiUrl}}/api/ingredients/category/{{getCategoryName}}
Accept: application/json

### Add ingredient
POST {{apiUrl}}/api/ingredients
Content-Type: application/json

{
  "name" : "",
  "categoryName" : ""
}

### Update ingredient
PUT {{apiUrl}}/api/ingredients
Content-Type: application/json

{
  "id" : "",
  "name" : "",
  "categoryName" : ""
}

### Delete ingredient
DELETE {{apiUrl}}/api/ingredients/{{deleteIngredientId}}
Content-Type: application/json