# =========================== Rcipes Controller ============================= #

@apiUrl = http://localhost:5000
@getRecipeName = *****                            
@getRecipeId = *****
@getCategoryName = *****
@deleteRecipeId = *****

# =============================================================================== #

### Get all recipes
GET {{apiUrl}}/api/recipes
Accept: application/json

### Get recipes by name
GET {{apiUrl}}/api/recipes/name/{{getRecipeName}}
Accept: application/json

### Get ingredient by id
GET {{apiUrl}}/api/recipes/id/{{getRecipeId}}
Accept: application/json

### Get recipes by category
GET {{apiUrl}}/api/recipes/category/{{getCategoryName}}
Accept: application/json

### Add ingredient
POST {{apiUrl}}/api/recipes
Content-Type: application/json

{
  "name" : "",
  "categoryName" : "",
  "shortDescription" : "",
  "preparation" : ""
}

### Update ingredient
PUT {{apiUrl}}/api/recipes
Content-Type: application/json

{
  "id" : "",
  "name" : "",
  "categoryName" : "",
  "shortDescription" : "",
  "preparation" : ""
}

### Delete ingredient
DELETE {{apiUrl}}/api/recipes/{{deleteRecipeId}}
Content-Type: application/json